# prometheus.yml

global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'flask-app'
    metrics_path: /metrics
    static_configs:
      - targets: ['https://proyek2-production-5975.up.railway.app:8080'] 
